apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
spec:
  ttlSecondsAfterFinished: 60 # for debugging
  backoffLimit: 1
  template:
    spec:
      containers:
      - name: migrate
        image: 1ek8/statusbus-migrate:latest
        command:
          - sh
          - -c
          - |
            bunx prisma migrate deploy --schema=./packages/store/prisma/schema.prisma && \
            bun run ./packages/store/seedRegion.ts ; sleep 600

        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: statusbus-secrets
              key: database-url
      restartPolicy: OnFailure
